Set https proxys to local and add outputs
GSA-TTS/FAC pull request #1174
Opened 2023-05-31 17:24 UTC by asteel-gsa

2023-06-07 05:10 UTC, mogul requested changes
Suggested updates to match attribute names to the variable names for the upstream clamav module, and uncomment our attributes now that they're supported.

2023-06-07 05:10 UTC, mogul commented on terraform/shared/modules/env/clamav.tf
>    # https_proxy   = module.https-proxy.https_proxy
```suggestion
  proxy_server   = module.https-proxy.domain
```

2023-06-07 05:10 UTC, mogul commented on terraform/shared/modules/env/clamav.tf
> +  # proxy_port     = module.https_proxy.port
```suggestion
  proxy_port     = module.https_proxy.port
```

2023-06-07 05:10 UTC, mogul commented on terraform/shared/modules/env/clamav.tf
> +  # proxy_username = module.https_proxy.username
```suggestion
  proxy_username = module.https_proxy.username
```

2023-06-07 05:10 UTC, mogul commented on terraform/shared/modules/env/clamav.tf
> +  # proxy_password = module.https_proxy.password
```suggestion
  proxy_password = module.https_proxy.password
```

2023-06-07 12:18 UTC, asteel-gsa commented
@mogul Do we need a new release for the 18f clamav `source = "github.com/18f/terraform-cloudgov//clamav?ref=v0.5.3"` to get the updates?

```
Error: Unsupported argument

  on ../shared/modules/env/clamav.tf line 20, in module "clamav":
  20:   proxy_port     = module.https_proxy.port

An argument named "proxy_port" is not expected here.

Error: Unsupported argument

  on ../shared/modules/env/clamav.tf line 21, in module "clamav":
  21:   proxy_username = module.https_proxy.username

An argument named "proxy_username" is not expected here.

Error: Unsupported argument

  on ../shared/modules/env/clamav.tf line 22, in module "clamav":
  22:   proxy_password = module.https_proxy.password

An argument named "proxy_password" is not expected here.
Error: Unsupported argument

  on ../shared/modules/env/clamav.tf line 20, in module "clamav":
  20:   proxy_port     = module.https_proxy.port

An argument named "proxy_port" is not expected here.

Error: Unsupported argument

  on ../shared/modules/env/clamav.tf line 21, in module "clamav":
  21:   proxy_username = module.https_proxy.username

An argument named "proxy_username" is not expected here.

Error: Unsupported argument

  on ../shared/modules/env/clamav.tf line 22, in module "clamav":
  22:   proxy_password = module.https_proxy.password

An argument named "proxy_password" is not expected here
```

2023-06-07 14:05 UTC, mogul commented
Yes we do! I'll take care of that in a bit

2023-06-07 20:45 UTC, mogul commented
Sorry it took me all day to get to this! 
https://github.com/18F/terraform-cloudgov/tree/v0.6.0

2023-06-07 22:54 UTC, mogul commented
Should be good to go now!

2023-06-08 13:17 UTC, JeanMarie-TTS reviewed
Why are we pulling a specific version of climb rather than the latest one?

2023-06-08 16:29 UTC, mogul approved these changes

2023-06-08 16:29 UTC, mogul commented
I was able to approve this since I didn't start the PR...! So I'm going to take care of it.

2023-06-08 16:29 UTC, merged