Update Federal Award model and ETL, add test for Federal Award.
GSA-TTS/FAC pull request #1476
Opened 2023-07-11 22:19 UTC by pluribus-tony

2023-07-11 23:33 UTC, JeanMarie-TTS requested changes
Why are making changes to package-lock.json?

2023-07-12 10:49 UTC, jadudm commented on backend/dissemination/models.py
> +    # TODO: Do we need to add any of the following?:
If the question is "will we need is_guaranteed, is_passed, or subrecipient_amount?," the answer will be yes.

2023-07-12 10:49 UTC, jadudm approved these changes
Good incremental add, pushing through... although, I'll wait to see why there were packaage-lock.json changes. Perhaps back those out?

2023-07-12 15:11 UTC, JeanMarie-TTS approved these changes

2023-07-12 15:12 UTC, merged