Only allow api.data.gov to access the API
GSA-TTS/FAC pull request #1663
Opened 2023-08-01 17:31 UTC by jadudm

This branch:

1. Introduces terraform config for PostgREST JWT secrets
2. Requires JWT secrets from `api.data.gov` in order to resolve API requests
3. Has tooling (Django commands) for creating JWT secrets

We have made the corresponding changes in the `api.data.gov` backend, and this should, therefore, make `api.fac.gov` available for public use. It should also mean that `fac-prod-postgrest.app.cloud.gov` will no longer accept API requests *except* from `api.data.gov`.

Secrets were added to `dev`, `staging`, ``preview` and `prod` in Github for workflows/deploys.

2023-08-01 17:47 UTC, mogul requested changes

2023-08-01 17:47 UTC, mogul commented on backend/dissemination/management/commands/create_api_jwt.py
> +    Runs sql scripts  to recreate views for the postgrest API.
```suggestion
    Creates JWT tokens for use in authenticating requests to PostgREST
```

2023-08-01 17:47 UTC, mogul commented on terraform/shared/modules/env/postgrest.tf
> +    PGRST_DB_ANON_ROLE : "anon",
```suggestion
    PGRST_DB_ANON_ROLE : "anon"
```

2023-08-01 17:47 UTC, mogul commented on terraform/shared/modules/env/postgrest.tf
> +    PGRST_JWT_SECRET: var.pgrst_jwt_secret
```suggestion
    PGRST_JWT_SECRET : var.pgrst_jwt_secret
```

2023-08-01 17:47 UTC, mogul commented on terraform/shared/modules/env/postgrest.tf
> +    PGRST_JWT_SECRET: var.pgrst_jwt_secret
Fixes fmt failure

2023-08-03 21:16 UTC, jadudm commented on backend/.profile
Need to merge `main` again.

2023-08-03 21:17 UTC, jadudm commented on backend/dissemination/README.md
> +creates a JWT secret. The passphrase must be [at least 32 characters long](https://postgrest.org/en/v10.2/tutorials/tut1.html#:~:text=32%20characters%20long.-,Note,-Unix%20tools%20can).
Add a UNIX one-liner for generating a reasonable secret for feeding into this.

2023-08-09 01:07 UTC, danswick commented
@jadudm per discussion, our test environment doesn't receive the JWT secret like the other environments do, which causes docker to substitute an empty string. I added a fallback value to `docker-compose-web`, which should only ever run in a GH actions test environment. Also did a little YAML standardization. See [this set of commits](https://github.com/GSA-TTS/FAC/pull/1663/files/e46e1824e485712991bc908e3a795c55f955ae5b..08ee40a181988a039eb5cbf4b7c5e280962dab72) for my changes.

2023-08-09 21:15 UTC, mogul approved these changes

2023-08-09 21:47 UTC, merged