Add preview module+space
GSA-TTS/FAC pull request #1700
Opened 2023-08-03 17:10 UTC by mogul

In addition to the `preview` module, there is a ton of refactoring in here as well, most of which I have tried to drag Alex through during pairing.

Separate from the code here, we have already: 

- Created the `meta` GitHub environment and populated it with the correct secrets (same as the previous `management` ones; they will move later)
- Created the `preview` CF space by hand because a bug in the Terraform provider prevents a non-admin user from doing that.
- Created a space-deployer service in the `preview` space
- Created the `preview` GitHub environment and populated it with the new deployer secrets
- Populated the JWT secret for PostgREST to use in securing the API
- Populated `SECRET_KEY` (matches `dev`; let me know how we could generate a unique one for `preview`!)

Note that once this is merged and applied, we should be

 - Remove the GitHub `management` environment since it's not used anymore.

SPECIAL NOTE: This PR also disables the management of space roles, which is something that `management` did. We will bring back that functionality in the next day or so (I think), but just know that if someone onboards/offboards before we restore that functionality, an admin is going to have to add/remove the SpaceDeveloper role by hand.

Future cleanup work:

- Find a new home for the `meta` deployer service and then destroy the CF `management` space since there's nothing else in it.
- Restore role management

2023-08-03 17:41 UTC, asteel-gsa approved these changes
Looks good, going to go through this all again with Tadhg/Jadud if you want to join us, just make sure everything looks good

2023-08-03 19:30 UTC, jadudm commented on terraform/meta/README.md
> +Among other things, this module...
```suggestion
Among other things, this module...
- Configures all the environment modules consistently
```

2023-08-03 19:31 UTC, jadudm commented on terraform/meta/README.md
> +- configures application security groups (ASGs) for the spaces
```suggestion
- (future) configures application security groups (ASGs) for the spaces
```

2023-08-03 19:31 UTC, jadudm commented on terraform/meta/README.md
> +- configures user access to those spaces
```suggestion
- (future) configures user access to those spaces
```

2023-08-03 19:31 UTC, jadudm commented on terraform/meta/README.md
> +- configures the spaces for dev, staging, and production
```suggestion
- (future) configures the spaces for dev, staging, and production
```

2023-08-03 19:31 UTC, jadudm commented on terraform/meta/README.md
> +- ensures the production space does not have SSH enabled
```suggestion
- (future) ensures the production space does not have SSH enabled
```

2023-08-03 19:33 UTC, jadudm commented on terraform/meta/bootstrap-env/deployer.tf-off
> +  populate_creds_locally    = true
```suggestion
  populate_creds_locally    = false
```

2023-08-03 19:41 UTC, jadudm commented on terraform/meta/bootstrap-env/modulefiles.tf
> +  content = templatefile("${path.module}/templates/variables.tf-template",
`variables-managed` does not use the template variables; does not need to be templated.

2023-08-03 19:41 UTC, jadudm commented on terraform/meta/bootstrap-env/modulefiles.tf
> +  content = templatefile("${path.module}/templates/providers.tf-template",
`providers` also does not use any of the templated variables.

2023-08-03 19:43 UTC, jadudm commented on terraform/meta/bootstrap-env/space.tf
> +  allow_ssh = var.name != "production" && var.name != "production-egress"
This could be a parameter of the space (e.g. instead of looking for the space name).

2023-08-03 19:50 UTC, jadudm commented on terraform/meta/bootstrap/main.tf
> +  populate_creds_locally = true
```suggestion
  populate_creds_locally = false
```

2023-08-03 19:59 UTC, jadudm commented on terraform/meta/main.tf
> +# Migrate state from the old addresses to the new addresses
You're 90% sure you don't need this... :waives hands:

2023-08-03 20:01 UTC, jadudm commented on terraform/preview/preview.tf
> +module "preview" {
If this is managed, we should have a blurb. If it isn't, this file is cool.

2023-08-03 20:01 UTC, jadudm commented on terraform/preview/preview.tf
> +module "preview" {
And, perhaps wants for parameters per `dev`, `staging`...

2023-08-03 20:04 UTC, jadudm requested changes
Changes requested; lots of great stuff.

2023-08-03 23:38 UTC, mogul commented
Addressed all points raised and re-requested a review from @jadudm.

2023-08-04 19:11 UTC, jadudm approved these changes
Full walk through; LGTM.

2023-08-04 19:12 UTC, merged