POM for check access (Access and Submission) page
GSA-TTS/FAC pull request #3621
Opened 2024-04-09 19:15 UTC by eazapata23

This PR is linked to #3485
This PR will close #3591 

In this PR:

- I added a Page objects page for `check-access.js`
- Removed `check-access.js` from support
- Modified `initialize-audit.js` to use new import and to instantiate an object from `accessAndSubmissionPage` class that calls the method `testValidAccess()`

# How to test:

- Run cypress as you normally would locally and run `full-submission.cy.js` test

## PR checklist: submitters

- [x]   Link to an issue if possible. If there’s no issue, describe what your branch does. Even if there is an issue, a brief description in the PR is still useful.
- [x]   List any special steps reviewers have to follow to test the PR. For example, adding a local environment variable, creating a local test file, etc.
- [ ]   For extra credit, submit a screen recording like [this one](https://github.com/GSA-TTS/FAC/pull/1821).
- [ ]   Make sure you’ve merged `main` into your branch shortly before creating the PR. (You should also be merging `main` into your branch regularly during development.)
- [ ]   Make sure you’ve accounted for any migrations. When you’re about to create the PR, bring up the application locally and then run `git status | grep migrations`. If there are any results, you probably need to add them to the branch for the PR. Your PR should have only **one** new migration file for each of the component apps, except in rare circumstances; you may need to delete some and re-run `python manage.py makemigrations` to reduce the number to one. (Also, unless in exceptional circumstances, your PR should not delete any migration files.)
- [x]   Make sure that whatever feature you’re adding has tests that cover the feature. This includes test coverage to make sure that the previous workflow still works, if applicable.
- [x]   Make sure the full-submission.cy.js [Cypress test](https://github.com/GSA-TTS/FAC/blob/main/docs/testing.md#end-to-end-testing) passes, if applicable.
- [x]   Do manual testing locally. Our tests are not good enough yet to allow us to skip this step. If that’s not applicable for some reason, check this box.
- [ ]   Verify that no Git surgery was necessary, or, if it was necessary at any point, repeat the testing after it’s finished.
- [ ]   Once a PR is merged, keep an eye on it until it’s deployed to dev, and do enough testing on dev to verify that it deployed successfully, the feature works as expected, and the happy path for the broad feature area (such as submission) still works.

## PR checklist: reviewers

- [ ]   Pull the branch to your local environment and run `make docker-clean; make docker-first-run && docker compose up`; then run `docker compose exec web /bin/bash -c "python manage.py test"`
- [ ]   Manually test out the changes locally, or check this box to verify that it wasn’t applicable in this case.
- [ ]   Check that the PR has appropriate tests. Look out for changes in HTML/JS/JSON Schema logic that may need to be captured in Python tests even though the logic isn’t in Python.
- [ ]   Verify that no Git surgery is necessary at any point (such as during a merge party), or, if it was, repeat the testing after it’s finished.

The larger the PR, the stricter we should be about these points.

2024-04-17 14:39 UTC, phildominguez-gsa requested changes
Works nicely! Just smallish stuff. One other thing to keep in mind keeping a consistent casing style for folders and files. From looking around we seem to use `snake_case` for folders and `kebab-case` for js and json files.

2024-04-17 14:39 UTC, phildominguez-gsa commented on backend/cypress/e2e/createNewAudit.cy.js
> +});
I'd put this newline back so GH stops complaining. Some of your other files are missing EoF newlines as well. [Here's](https://stackoverflow.com/a/729795) why they're good.

2024-04-17 14:39 UTC, phildominguez-gsa commented on backend/cypress/e2e/search-tests.cy.js
> +});
```suggestion
    search.testSummaryReport();
  });

});
```

2024-04-17 14:39 UTC, phildominguez-gsa commented on backend/cypress/e2e/search-tests.cy.js
> +//advanced search test
I think either remove this commented out stuff, or put a comment explaining why it's commented out.

2024-04-17 14:39 UTC, phildominguez-gsa commented on backend/cypress/pageObjects/general-info.js
> +class GeneralInfoForm {
```suggestion
import auditorEmailField from '../fixtures/genInfoData/auditorEmailField.json';

class GeneralInfoForm {
```

2024-04-17 14:39 UTC, phildominguez-gsa commented on backend/cypress/pageObjects/general-info.js
> +    selectAuditTypeAndPeriod() {
```suggestion
    }

    selectAuditTypeAndPeriod() {
```

2024-04-17 14:39 UTC, phildominguez-gsa commented on backend/cypress/pageObjects/general-info.js
> +export default GeneralInfoForm;
```suggestion
    }
}

export default GeneralInfoForm;
```

2024-04-17 14:39 UTC, phildominguez-gsa commented on backend/cypress/pageObjects/searchPage.js
> +export default searchPage;
```suggestion
    }
}

export default searchPage;

```

2024-04-19 16:35 UTC, closed without merging

2024-04-19 16:36 UTC, eazapata23 commented
this PR is no longer needed and will be closed since the work has been done in this PR #3574