Make first draft of  sequence diagram
GSA-TTS/FAC pull request #810
Opened 2023-02-17 19:31 UTC by JeanMarie-TTS

Took a first cut at creating a sequence diagram. Need collaborators and reviewers to get this to completion.
Also need help creating a png file as something is broken on my laptop.

2023-02-22 00:00 UTC, tadhg-ohiggins commented
Both auditee and auditor are likely to make changes to the Excel files, so both of those should reflect pulling down the Excel files and then uploading them. The auditors do not only submit findings, but a lot of the other info as well. Who submits what info appears to depend a lot on the individual user(s).

Certification must be done both by someone from the auditor and someone from the auditee; this diagram makes it seem as though only the auditee performs that action, which doesn't match my understanding.

`s/Agebcy/Agency` throughout.

For the agency users, I'm not clear on the direction of the arrows; if the fourth user in the user list is the agency user, shouldn't access start from them rather than from the agency? And in either case, shouldn't line one (“accesses FAC”) and line seven (“returns API results”), as well as some of the others, end up going to the same place?

2023-02-22 01:34 UTC, JeanMarie-TTS commented
@tadhg-ohiggins , the typo caused the agency access to be rendered incorrectly. 
My assumption is that the auditor makes submissions on behalf of a grantee and that it should suffice to show the grantee actions for this case.
Is there a generic term to denote what the auditor submits? I used 'Findings', but we need something broader.
I need to understand better what the auditor certifies.
Will make another commit now so you can comment on my changes.

2023-03-10 23:27 UTC, tadhg-ohiggins requested changes

2023-03-10 23:27 UTC, tadhg-ohiggins commented on docs/architecture/diagrams/src/FAC_Sequence.puml
> +FAC -> Grantee : Mahed previous submission available for editing
s/Mahed/Makes

2023-03-10 23:27 UTC, tadhg-ohiggins commented on docs/architecture/diagrams/src/FAC_Sequence.puml
> +S3 -> FAC : Fetches previously saved xlsx docs
“docs” here should be “documents”, or “documents” elsewhere should be “docs”, for consistency.

2023-03-11 00:24 UTC, tadhg-ohiggins approved these changes

2023-03-11 01:29 UTC, merged